### ISSUE TITLE
How to use the library?

### ISSUE THREAD

**Issue by hackin88** [digitickets/omnipay-datacash#1]
Hello

good afternoon

How to use the library?

If possible create a folder containing examples library usage examples

thank you

**Comment by coatesap** [comment]
Hi @hackin88 - it's probably worth having a look at the main OmniPay page on GitHub, as this contains some good examples of how to use the OmniPay library. The actual driver you are using (PayPal, DataCash, etc) shouldn't make a huge difference to how you implement your payment processing code. DataCash is actually fairly standard in this respect.

As you gain experience using the library, please feel free to submit pull requests with examples, and I'll merge these in for other users to benefit from.
